### ISSUE TITLE
Missing dependencies to create Windows executables

### ISSUE THREAD

**Issue by Fabriz1o** [schyczewski/funcoin#3]
En su video (https://www.youtube.com/watch?v=_ti-d5t1WX8) descarga unas dependencias en la carpeta "entradas", sin embargo en https://pastebin.com/RTZX6c7n no están todas.

In the video:
![image](https://user-images.githubusercontent.com/16902577/64072127-1b0f9700-cc4f-11e9-94ea-05abc4dffabd.png)

Dependencies in Pastebin:
![image](https://user-images.githubusercontent.com/16902577/64072144-45615480-cc4f-11e9-96fd-5515569e6b9f.png)

Missing:
bitcoin08-deps-win32-gitian-r13.zip
boost-win32-1.55.0-gitian-r6.zip
qt-win32-4.8.5-gitian-r8.zip

Could you share these files please? I have looked for them and I have not had luck.

**Comment by Exxhal** [comment]
The files are there , just look for theme. Good luck.

**Comment by ramzialhaddad** [comment]
You make those with the commands he provided
```
./bin/gbuild ../funcoin/contrib/gitian-descriptors/boost-win32.yml
mv build/out/boost-*.zip inputs/
 
./bin/gbuild ../funcoin/contrib/gitian-descriptors/deps-win32.yml
mv build/out/bitcoin*.zip inputs/
 
./bin/gbuild ../funcoin/contrib/gitian-descriptors/qt-win32.yml
mv build/out/qt*.zip inputs/```

**Comment by WireROP** [comment]
No such File or directory
            Come!
    if it's not fun
                     wheres the FUN?

**Comment by waltercoin-project** [comment]
I tried this, and the first two commands worked. The third one is giving me trouble, and preventing me from continuing on with the project.

Below is what I'm currently getting when I try and execute the third gbuild command:

```
debian@debian:~/gitian-builder$ ./bin/gbuild ../waltercoin/contrib/gitian-descriptors/qt-win32.yml
sha256sum: qt-everywhere-opensource-src-4.8.5.tar.gz: No such file or directory
--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog* ubuntu-minimal*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1289 kB disk space will be freed.
(Reading database ... 16075 files and directories currently installed.)
Removing ubuntu-minimal ...
Removing rsyslog ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Purging configuration files for rsyslog ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed.
Processing triggers for ureadahead ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
tar: qt-everywhere-opensource-src-4.8.5.tar.gz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while (log in var/install.log)
^C./bin/gbuild:23:in `system': Interrupt
        from ./bin/gbuild:23:in `system!'
        from ./bin/gbuild:138:in `build_one_configuration'
        from ./bin/gbuild:339:in `block (2 levels) in <main>'
        from ./bin/gbuild:334:in `each'
        from ./bin/gbuild:334:in `block in <main>'
        from ./bin/gbuild:332:in `each'
        from ./bin/gbuild:332:in `<main>'

debian@debian:~/gitian-builder$ tar: qt-everywhere-opensource-src-4.8.5.tar.gz: Cannot stat: No such file or directory
-bash: tar:: command not found
debian@debian:~/gitian-builder$ ./bin/gbuild ../waltercoin/contrib/gitian-descriptors/qt-win32.yml./bin/gbuild ../waltercoin/contrib/gitian-descriptors/qt-win32.yml
/usr/lib/ruby/2.1.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - ../waltercoin/contrib/gitian-descriptors/qt-win32.yml./bin/gbuild (Errno::ENOENT)
        from /usr/lib/ruby/2.1.0/psych.rb:464:in `open'
        from /usr/lib/ruby/2.1.0/psych.rb:464:in `load_file'
        from ./bin/gbuild:244:in `<main>'
debian@debian:~/gitian-builder$ ./bin/gbuild ../waltercoin/contrib/gitian-descriptors/qt-win32.yml
sha256sum: qt-everywhere-opensource-src-4.8.5.tar.gz: No such file or directory
--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog* ubuntu-minimal*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1289 kB disk space will be freed.
(Reading database ... 16075 files and directories currently installed.)
Removing ubuntu-minimal ...
Removing rsyslog ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Purging configuration files for rsyslog ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed.
Processing triggers for ureadahead ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
tar: qt-everywhere-opensource-src-4.8.5.tar.gz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while (log in var/install.log)
^C./bin/gbuild:23:in `system': Interrupt
        from ./bin/gbuild:23:in `system!'
        from ./bin/gbuild:138:in `build_one_configuration'
        from ./bin/gbuild:339:in `block (2 levels) in <main>'
        from ./bin/gbuild:334:in `each'
        from ./bin/gbuild:334:in `block in <main>'
        from ./bin/gbuild:332:in `each'
        from ./bin/gbuild:332:in `<main>'

debian@debian:~/gitian-builder$ ./bin/gbuild ../waltercoin/contrib/gitian-descriptors/qt-win32.yml
sha256sum: qt-everywhere-opensource-src-4.8.5.tar.gz: No such file or directory
--- Building for precise amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog* ubuntu-minimal*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1289 kB disk space will be freed.
(Reading database ... 16075 files and directories currently installed.)
Removing ubuntu-minimal ...
Removing rsyslog ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Purging configuration files for rsyslog ...
dpkg: warning: while removing rsyslog, directory '/etc/apparmor.d/local' not empty so not removed.
Processing triggers for ureadahead ...
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
tar: qt-everywhere-opensource-src-4.8.5.tar.gz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Updating apt-get repository (log in var/install.log)
^C./bin/gbuild:23:in `system': Interrupt
        from ./bin/gbuild:23:in `system!'
        from ./bin/gbuild:117:in `build_one_configuration'
        from ./bin/gbuild:339:in `block (2 levels) in <main>'
        from ./bin/gbuild:334:in `each'
        from ./bin/gbuild:334:in `block in <main>'
        from ./bin/gbuild:332:in `each'
        from ./bin/gbuild:332:in `<main>'

debian@debian:~/gitian-builder$
```

Does anyone have any ideas on how to fix this? Thanks!

**Comment by drclive** [comment]
Did you find the dependencies? I have exactly the same issue.

**Comment by drclive** [comment]
> You make those with the commands he provided
> 
> ```
> ./bin/gbuild ../funcoin/contrib/gitian-descriptors/boost-win32.yml
> mv build/out/boost-*.zip inputs/
>  
> ./bin/gbuild ../funcoin/contrib/gitian-descriptors/deps-win32.yml
> mv build/out/bitcoin*.zip inputs/
>  
> ./bin/gbuild ../funcoin/contrib/gitian-descriptors/qt-win32.yml
> mv build/out/qt*.zip inputs/```
> ```

The third command fails because this file bitcoin08-deps-win32-gitian-r13.zip is missing.

**Comment by Vitalik-Hakim** [comment]
> > You make those with the commands he provided
> > ```
> > ./bin/gbuild ../funcoin/contrib/gitian-descriptors/boost-win32.yml
> > mv build/out/boost-*.zip inputs/
> >  
> > ./bin/gbuild ../funcoin/contrib/gitian-descriptors/deps-win32.yml
> > mv build/out/bitcoin*.zip inputs/
> >  
> > ./bin/gbuild ../funcoin/contrib/gitian-descriptors/qt-win32.yml
> > mv build/out/qt*.zip inputs/```
> > ```
> 
> The third command fails because this file bitcoin08-deps-win32-gitian-r13.zip is missing.

Yeah me too this is frustrating please hellp!!

**Comment by texasatoshi** [comment]
I wasn't even able to get Precise running as it's no longer supported.
Have any of you had success with creating the Windows exe?
